version: '3'

services:
  db:
    image: mariadb
    labels:
      - "nextcloud"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    labels:
      - "nextcloud"
    restart: always

  app:
    image: nextcloud:apache
    labels:
      - "nextcloud"
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
      - app.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    labels:
      - "nextcloud"
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      - "nextcloud"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    labels:
      - "nextcloud"
    restart: always
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
      - app
    networks:
      - proxy-tier

  jobber:
    build: ./jobber
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /backup:/backup
      - ./shellScript/backup.sh:/backup.sh:ro
      - ~/ssh.pas:/root/ssh.pas:ro
    environment:
      - JOBS_NOTIFY_CMD=/bin/bash
      - JOB_NAME1=Backup
      - JOB_COMMAND1=/bin/bash /backup.sh
      - JOB_TIME1=0 0 8 * * 3 #Exec per Week at Wed. 8 a.m.
      - JOB_NOTIFY_ERR1=false
      - JOB_NOTIFY_FAIL1=true

volumes:
  db:
    labels:
      - "nextcloud"
  nextcloud:
    labels:
      - "nextcloud"
  conf:
    labels:
      - "nextcloud"
  dhparam:
    labels:
      - "nextcloud"
  certs:
    labels:
      - "nextcloud"
  vhost:
    labels:
      - "nextcloud"
  html:
    labels:
      - "nextcloud"

networks:
  proxy-tier:
