version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    labels:
      - "nextcloud"
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    labels:
     - "nextcloud"
    restart: always

  app:
    image: nextcloud:apache
    labels:
      - "nextcloud"
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    labels:
      - "nextcloud"
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - "nextcloud"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    labels:
    - "nextcloud"
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  ofelia:
    image: mcuadros/ofelia
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backup:/backup
      - ./backup.sh:/backup.sh
    labels:
        #ofelia.job-local.backupjob.schedule: "0 7 * * 3"
      ofelia.job-local.backupjob.schedule: "*/5 * * * *"
      ofelia.job-local.backupjob.command: "/bin/bash /backup.sh"
volumes:
  db:
    labels:
      - "nextcloud"
  nextcloud:
    labels:
      - "nextcloud"
  certs:
    labels:
      - "nextcloud"
  vhost.d:
    labels:
      - "nextcloud"
  html:
    labels:
      - "nextcloud"

networks:
  proxy-tier:
