version: '3.7'

x-labels:
  labels: &default-label
    nextcloud:

services:
  db:
    image: mariadb
    labels: *default-label
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    labels: *default-label
    restart: always

  app:
    image: nextcloud:apache
    labels: *default-label
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - .env
      - db.env
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      # Comma-seperated
      - VIRTUAL_HOST=${LETSENCRYPT_HOST}
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    labels: *default-label
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  jobber:
    build: ./jobber
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /backup:/backup
      - ./shellScript:/script:ro
      - ~/ssh.pas:/root/ssh.pas:ro
    environment:
      - JOB_NAME1=Backup
      - JOB_COMMAND1=/bin/bash /script/backup.sh && /bin/bash /script/upload.sh
      - JOB_TIME1=0 0 0 * * 3 #Exec per Week at UTC Wed. 0 a.m.
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true

volumes:
  db:
    labels: *default-label
  nextcloud:
    labels: *default-label

networks:
  proxy-tier:
    external: true
    name: proxy-tier
